# Generated by Django 4.0.4 on 2022-05-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0007_alter_review_is_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(max_length=50),
        ),
    ]
