# Generated by Django 4.0.4 on 2022-05-27 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ercf', '0008_rename_is_for_review_author_alter_review_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='com', to=settings.AUTH_USER_MODEL),
        ),
    ]
