# Generated by Django 4.0.4 on 2022-05-27 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0011_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.TextField(default='title'),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.TextField(default='id'),
        ),
    ]
