# Generated by Django 4.0.4 on 2022-05-28 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0012_video_title_alter_video_video_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='topic',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ercf.topic'),
        ),
    ]
