# Generated by Django 4.0.4 on 2022-05-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0013_video_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('picture', models.ImageField(upload_to='')),
                ('file', models.FileField(upload_to='')),
            ],
        ),
    ]
