# Generated by Django 4.0.4 on 2022-05-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0014_sample'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='post_id',
            field=models.TextField(default='gang'),
            preserve_default=False,
        ),
    ]
