# Generated by Django 4.0.4 on 2022-05-29 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0017_remove_review_post_title_alter_review_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='post_id',
            field=models.DateTimeField(),
        ),
    ]
