# Generated by Django 4.0.4 on 2022-05-29 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0018_alter_review_post_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='post_date',
            field=models.DateTimeField(default='1111-11-11 11:11'),
        ),
        migrations.AddField(
            model_name='review',
            name='post_title',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='review',
            name='post_id',
            field=models.TextField(default=''),
        ),
    ]
