# Generated by Django 4.0.4 on 2022-05-29 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0019_review_post_date_review_post_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='author_identity',
            field=models.TextField(default='1'),
            preserve_default=False,
        ),
    ]
