# Generated by Django 4.0.4 on 2022-06-14 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0020_post_author_identity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
