# Generated by Django 4.0.4 on 2022-06-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0021_alter_sample_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='file',
        ),
        migrations.AddField(
            model_name='sample',
            name='images',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
