# Generated by Django 4.0.4 on 2022-06-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0022_remove_sample_file_sample_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='picture',
            field=models.ImageField(default='dafd', upload_to='images/'),
            preserve_default=False,
        ),
    ]
