# Generated by Django 4.0.4 on 2022-06-14 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0023_alter_sample_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='picture',
            field=models.ImageField(upload_to='static/images/'),
        ),
    ]
