# Generated by Django 4.0.4 on 2022-06-14 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0024_alter_sample_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
