# Generated by Django 4.0.4 on 2022-06-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0026_alter_sample_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='url',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='picture',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
