# Generated by Django 4.0.4 on 2022-06-16 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0028_sample_music_url_alter_sample_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='images',
            new_name='s1',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='music_url',
            new_name='s10_url',
        ),
        migrations.AddField(
            model_name='sample',
            name='s10',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='s1_url',
            field=models.TextField(default='?', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='s2',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='s2_url',
            field=models.TextField(default='?', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='s3',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='s3_url',
            field=models.TextField(default='?', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='s4',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='s4_url',
            field=models.TextField(default='?', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='s5',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='s5_url',
            field=models.TextField(default='?', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='s6',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='s6_url',
            field=models.TextField(default='?', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='s7',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='s7_url',
            field=models.TextField(default='?', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='s8',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='s8_url',
            field=models.TextField(default='?', null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='s9',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='sample',
            name='s9_url',
            field=models.TextField(default='?', null=True),
        ),
    ]
