# Generated by Django 4.0.4 on 2022-06-17 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0029_rename_images_sample_s1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
