# Generated by Django 4.0.4 on 2022-06-21 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0031_video_audio_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('picture', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
