# Generated by Django 4.0.4 on 2022-06-22 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ercf', '0035_album_artist_album_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='des',
            field=models.CharField(max_length=1000),
        ),
    ]
